#!/bin/busybox sh

set -o pipefail

mount -n -t proc proc /proc || fatal "Failure mount /proc"
echo 0 > /proc/sys/kernel/printk

mount -n -t devtmpfs devtmpfs /dev || fatal "Failure mount /dev"

exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

mkdir -m 0755 /dev/pts || fatal "Failure create directory /dev/pts with perms 755"
mount -n -t devpts -o gid=5,mode=0620 devpts /dev/pts || fatal "Failure mount /dev/pts"

mount -n -t sysfs sysfs /sys || fatal "Failure mount /dev/pts"
mount -n -t tmpfs -o rw,nodev,mode=755 none /run || fatal "Failure mount /run"

cat /BANNER

DEBUG=yes

source /init-base.functions
source /init-platform.functions

# Set up busybox'es symlinks
/bin/busybox --install -s || fatal "Failure install busybox symlinks"

# touch /var/log/lastlog || fatal "Failure create /var/log/lastlog"

# ln -s /proc/mounts /etc/mtab || fatal "Failure link /etc/mtab -> /proc/mounts"

# 
# PreBoot should not to reboot device without eth0.
# Originally it was added for buggy-laptop C3C58ES#AKD
# but now we trying to remove network stack from preboot at all
# so this reboot, probably, may be implemented inside initramfs so on...
#
# if ! /sbin/ip link show eth0 >/dev/null 2>&1; then
#     warn "A network device 'eth0' is not found. Reboot in 5 seconds..."
#     sleep 5
#     reboot -f
# fi

CUSTOM_VOLUME_GROUPS=""
PREBOOT_CMDLINE=""

exec 3>&2 # Make copy of stderr on another FD 3 to be able to redirect stderr from list_boot_device_candidates
BOOT_CANDIDATE_DEVS=$(list_boot_device_candidates 2>&3)
exec 3>&- # Close FD 3

info "Found boot device candidates: $(echo ${BOOT_CANDIDATE_DEVS} | xargs)"
for BOOT_CANDIDATE_DEV in ${BOOT_CANDIDATE_DEVS}; do
    if [ -n "${CUSTOM_VOLUME_GROUPS}" -a -n "${PREBOOT_CMDLINE}" ]; then
        # We found all necessary information on previous boot devices
        # so nothing ti do anymore
        break
    fi

    info "Mount boot device candidate: ${BOOT_CANDIDATE_DEV} ..."
    if ! mount -t vfat -o ro "${BOOT_CANDIDATE_DEV}" /mnt; then
        info "Unable to mount '${BOOT_CANDIDATE_DEV}'. Skipped."
        continue
    fi

    if [ -n "${PREBOOT_CMDLINE}" ]; then
        info "Skip reading PREBOOT_CMDLINE due to set early"
    elif [ -f /mnt/OSFORDEV_CMDLINE ]; then
        info "File OSFORDEV_CMDLINE found on ${BOOT_CANDIDATE_DEV}"
        RAW_PREBOOT_CMDLINE=$(cat /mnt/OSFORDEV_CMDLINE)
        for RAW_PREBOOT_ARG in ${RAW_PREBOOT_CMDLINE}; do
            PREBOOT_CMDLINE="${PREBOOT_CMDLINE} ${RAW_PREBOOT_ARG}"
        done
        # trim spaces
        PREBOOT_CMDLINE=$(echo "${PREBOOT_CMDLINE}" | xargs)
        info "PREBOOT_CMDLINE: '${PREBOOT_CMDLINE}'"
    else
        info "No file OSFORDEV_CMDLINE on ${BOOT_CANDIDATE_DEV}"
    fi
    
    # -z "${CUSTOM_VOLUME_GROUPS}" will help to use osfordev-vgs-assembler.sh from
    # first boot device, and ignore next boot device candidates
    # (in case when few boot devices do have osfordev-vgs-assembler.sh file)
    if [ -z "${CUSTOM_VOLUME_GROUPS}" -a -f /mnt/osfordev-vgs-assembler.sh -a ! -x /tmp/osfordev-vgs-assembler.sh ]; then
        info "Script /osfordev-vgs-assembler.sh found on ${BOOT_CANDIDATE_DEV} ..."
        cp -a /mnt/osfordev-vgs-assembler.sh /tmp/osfordev-vgs-assembler.sh
    fi

    info "Umount boot device candidate: ${BOOT_CANDIDATE_DEV} ..."
    umount "${BOOT_CANDIDATE_DEV}" || fatal "Unable umount ${BOOT_CANDIDATE_DEV}"

    if [ -z "${CUSTOM_VOLUME_GROUPS}" -a -x /tmp/osfordev-vgs-assembler.sh ]; then
        info "Calling VGs assembler script to up VGs ..."
        RAW_VOLUME_GROUPS=$(/tmp/osfordev-vgs-assembler.sh up)
        for RAW_VOLUME_GROUP in ${RAW_VOLUME_GROUPS}; do
            CUSTOM_VOLUME_GROUPS="${CUSTOM_VOLUME_GROUPS} ${RAW_VOLUME_GROUP}"
        done
        # trim spaces
        CUSTOM_VOLUME_GROUPS=$(echo "${CUSTOM_VOLUME_GROUPS}" | xargs)

        if [ -z "${CUSTOM_VOLUME_GROUPS}" ]; then
            fatal "Contract violation. Custom VGs assembler did not return volume group name(s)."
        fi

        info "Custom volume groups: '${CUSTOM_VOLUME_GROUPS}'"
    fi
done

if [ -n "${CUSTOM_VOLUME_GROUPS}" ]; then
    # By contract, custom VGs assembler script must return root VG first
    VGROOT=$(echo "${CUSTOM_VOLUME_GROUPS}" | cut -d' ' -f 1)
else
    VGROOT="vgroot"

    info "Scanning for volume groups ..."
    /sbin/vgscan || fatal "/sbin/vgscan: Failure scan volume groups"

    info "Activating volume group: '${VGROOT}' ..."
    /sbin/vgchange --activate y "${VGROOT}" || fatal "/sbin/vgchange: Failure activate volume group '${VGROOT}'"
fi

info "Mounting 'system' logical volume ..."
mount -o ro "/dev/${VGROOT}/system" /mnt || fatal "mount: Failure mount logical volume '/dev/${VGROOT}/system'"

BOOT_CMDLINE=""
if [ -f /mnt/boot/OSFORDEV_CMDLINE ]; then
    RAW_BOOT_CMDLINE="$(cat /mnt/boot/OSFORDEV_CMDLINE)"
    for RAW_BOOT_ARG in ${RAW_BOOT_CMDLINE}; do
        BOOT_CMDLINE="${BOOT_CMDLINE} ${RAW_BOOT_ARG}"
    done
    # trim spaces
    BOOT_CMDLINE=$(echo "${BOOT_CMDLINE}" | xargs)

    info "System volume '/boot/OSFORDEV_CMDLINE': ${BOOT_CMDLINE}"
else
    info "System volume does not have '/boot/OSFORDEV_CMDLINE'"
fi

#invite_to_shell 3

KERNEL_IMAGE=$(resolve_kernel_file_name)
info "Resolve kernel file name: ${KERNEL_IMAGE}"

info "Kernel args: ${PREBOOT_CMDLINE} ${BOOT_CMDLINE}"
info "Loading kernel and initramfs into kexec ..."
kexec --load /mnt/boot/${KERNEL_IMAGE} --initrd=/mnt/boot/initramfs.cpio.gz --append="${PREBOOT_CMDLINE} ${BOOT_CMDLINE}" || fatal "kexec: Unable to load kernel/initrams."

info "Umounting 'system' logical volume ..."
umount /mnt || fatal "Failure umount logical volume '/dev/${VGROOT}/system'"

if [ -n "${CUSTOM_VOLUME_GROUPS}" ]; then
    info "Calling VGs assembler script to down VGs ..."
    /tmp/osfordev-vgs-assembler.sh down || fatal "VGs down scriptd failed."
else
    info "Deactivating VG '${VGROOT}' ..."
    /sbin/vgchange --activate n "${VGROOT}" || fatal "Unable to de-activate volume group '${VGROOT}'."
fi

info "Run kexec ..."
# invite_to_shell 2
kexec --exec || fatal "kexec: Unable to execute."
